In [1]:
import numpy as np

# Scalars

In [17]:
s = np.array(5)

In [18]:
s.shape

()

In [21]:
x = s + 3
x.shape

()

# Vectors

In [22]:
v = np.array([1,2,3])
v.shape

(3,)

In [23]:
x = v[1]
x

2

In [24]:
x = v[1:]
x

array([2, 3])

# Matrices

In [29]:
m = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
m.shape

(3, 3)

In [30]:
x = m + 3
x

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [32]:
x[2][1]

11

# Tensors

In [34]:
t = np.array([[[[ 1],[ 2]],
               [[ 3],[ 4]],
               [[ 5],[ 6]]],
              [[[ 7],[ 8]],
               [[ 9],[10]],
               [[11],[12]]],
              [[[13],[14]],
               [[15],[16]],
               [[17],[18]]]])
t

array([[[[ 1],
         [ 2]],

        [[ 3],
         [ 4]],

        [[ 5],
         [ 6]]],


       [[[ 7],
         [ 8]],

        [[ 9],
         [10]],

        [[11],
         [12]]],


       [[[13],
         [14]],

        [[15],
         [16]],

        [[17],
         [18]]]])

In [35]:
t.shape

(3, 3, 2, 1)

In [36]:
t[2][1][1][0]

16

# Element-wise Matrix Operations

In [41]:
a = np.array([[1,3],[5,7]])
a

array([[1, 3],
       [5, 7]])

In [49]:
x = a * 5
x

array([[ 5, 15],
       [25, 35]])

In [50]:
x += x
x

array([[10, 30],
       [50, 70]])

In [51]:
x *= x
x

array([[ 100,  900],
       [2500, 4900]])

In [52]:
x *= 0
x

array([[0, 0],
       [0, 0]])

In [53]:
b = np.array([[2,4],[6,8]])
b

array([[2, 4],
       [6, 8]])

In [54]:
a + b

array([[ 3,  7],
       [11, 15]])

# Element-wise Multiplication

In [55]:
m = np.array([[1,2,3],[4,5,6]])
m

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
n = m * 0.25
n

array([[ 0.25,  0.5 ,  0.75],
       [ 1.  ,  1.25,  1.5 ]])

In [57]:
m * n

array([[ 0.25,  1.  ,  2.25],
       [ 4.  ,  6.25,  9.  ]])

In [58]:
np.multiply(m, n)

array([[ 0.25,  1.  ,  2.25],
       [ 4.  ,  6.25,  9.  ]])

# Matrix Product

In [59]:
a = np.array([[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [60]:
a.shape

(2, 4)

In [61]:
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [63]:
b.shape

(4, 3)

In [64]:
c = np.matmul(a, b)
c

array([[ 70,  80,  90],
       [158, 184, 210]])

In [65]:
c.shape

(2, 3)

In [66]:
np.matmul(b, a)

ValueError: shapes (4,3) and (2,4) not aligned: 3 (dim 1) != 2 (dim 0)

# NumPy's dot function

In [67]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [68]:
np.dot(a,a)

array([[ 7, 10],
       [15, 22]])

In [69]:
a.dot(a) 

array([[ 7, 10],
       [15, 22]])

In [70]:
np.matmul(a,a)

array([[ 7, 10],
       [15, 22]])

# Transpose

In [71]:
m = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
m

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [72]:
m.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [74]:
# You need to be careful with how you modify objects, because they are sharing the same data.

m_t = m.T
m_t[3][1] = 200
m_t

array([[  1,   5,   9],
       [  2,   6,  10],
       [  3,   7,  11],
       [  4, 200,  12]])

In [75]:
m

array([[  1,   2,   3,   4],
       [  5,   6,   7, 200],
       [  9,  10,  11,  12]])

In [76]:
inputs = np.array([[-0.27,  0.45,  0.64, 0.31]])
inputs

array([[-0.27,  0.45,  0.64,  0.31]])

In [77]:
weights = np.array([[0.02, 0.001, -0.03, 0.036], \
    [0.04, -0.003, 0.025, 0.009], [0.012, -0.045, 0.28, -0.067]])
weights

array([[ 0.02 ,  0.001, -0.03 ,  0.036],
       [ 0.04 , -0.003,  0.025,  0.009],
       [ 0.012, -0.045,  0.28 , -0.067]])

In [78]:
np.matmul(inputs, weights.T)

array([[-0.01299,  0.00664,  0.13494]])

In [79]:
np.matmul(weights, inputs.T)

array([[-0.01299],
       [ 0.00664],
       [ 0.13494]])

In [ ]:
inputs.min